#!/usr/bin/env bash
# Raven — one-liner install
#
#   curl -fsSL <raw-url>/scripts/install.sh | bash
#
# Clones the repo (if not already inside it), sets up Python venv,
# installs deps, and builds the dashboard.
set -euo pipefail

REPO_URL="${RAVEN_REPO_URL:-https://github.com/jaekanglee/RavenCode.git}"
INSTALL_DIR="${RAVEN_INSTALL_DIR:-$HOME/Raven}"

# --- detect: inside repo already, or fresh clone? ---
if [ -f "$(pwd)/raven/__init__.py" ]; then
  ROOT="$(pwd)"
  echo "=== Raven install (in-repo) ==="
else
  ROOT="$INSTALL_DIR"
  echo "=== Raven install → $ROOT ==="
  if [ -d "$ROOT/.git" ]; then
    echo "--- pulling latest ---"
    git -C "$ROOT" pull --ff-only
  else
    echo "--- cloning ---"
    git clone --depth 1 "$REPO_URL" "$ROOT"
  fi
fi
cd "$ROOT"

# --- prerequisites (macOS auto-bootstrap) ---
if [ "$(uname)" = "Darwin" ]; then
  if ! command -v git >/dev/null || ! command -v python3 >/dev/null; then
    echo "--- Xcode Command Line Tools 설치 (python3 + git) ---"
    xcode-select --install 2>/dev/null || true
    echo "    설치 대화상자에서 '설치' 클릭 후 완료되면 Enter..."
    read -r
  fi
  if ! command -v node >/dev/null; then
    if ! command -v brew >/dev/null; then
      echo "--- Homebrew 설치 ---"
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
    echo "--- Node.js 설치 ---"
    brew install node
  fi
fi
command -v python3 >/dev/null || { echo "ERROR: python3 not found"; exit 1; }
command -v node    >/dev/null || { echo "ERROR: node not found (need >=18)"; exit 1; }
command -v git     >/dev/null || { echo "ERROR: git not found"; exit 1; }

PY_VER=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
echo "  python: $PY_VER  node: $(node -v)"

# --- Python venv + deps ---
VENV="$ROOT/scripts/.venv"
if [ ! -d "$VENV" ]; then
  echo "--- creating venv ---"
  python3 -m venv "$VENV"
elif ! "$VENV/bin/pip" --version >/dev/null 2>&1; then
  echo "--- stale venv detected (moved repo?), recreating ---"
  rm -rf "$VENV"
  python3 -m venv "$VENV"
fi
echo "--- installing python deps ---"
"$VENV/bin/python3" -m pip install -q --upgrade pip
"$VENV/bin/python3" -m pip install -q -r requirements.txt

# --- Dashboard build ---
echo "--- building dashboard ---"
cd "$ROOT/dashboard"
npm install --silent
npm run build --silent

# --- `raven` 명령어 shim ---
# raven 패키지는 설치되지 않고 체크아웃에서 PYTHONPATH로 실행된다(Makefile 참조).
# 그래서 entry point가 없다 — 체크아웃과 venv를 고정한 shim을 PATH에 깔아준다.
# 이게 있어야 `raven update` 같은 명령을 어디서든 칠 수 있다.
BIN_DIR="${RAVEN_BIN_DIR:-$HOME/.local/bin}"
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/raven" << SHIM
#!/usr/bin/env bash
# Generated by scripts/install.sh — 체크아웃: $ROOT
exec "$VENV/bin/python" -m raven.cli "\$@"
SHIM
chmod +x "$BIN_DIR/raven"
echo "--- installed \`raven\` → $BIN_DIR/raven ---"

# --- done ---
echo ""
echo "=== install complete ==="
echo ""
case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *)
    echo "  ⚠️  $BIN_DIR 가 PATH에 없습니다. 셸 설정에 추가하세요:"
    echo "      export PATH=\"\$HOME/.local/bin:\$PATH\""
    echo ""
    ;;
esac
echo "  CLI:"
echo "    raven --help"
echo "    raven update          # 최신 소스로 자체 업데이트"
echo ""
echo "  Start API server:"
echo "    $VENV/bin/python -m raven.api"
echo ""
echo "  Start with external access (Tailscale/LAN):"
echo "    $VENV/bin/python -m raven.api --host 0.0.0.0"
echo ""
echo "  Dashboard (after API start):"
echo "    http://127.0.0.1:8765"
